### ISSUE TITLE
missing dependency on semver

### ISSUE THREAD

**Issue by nphollon** [avh4/elm-upgrade#10]
Trying to run elm-upgrade gave me this error message:

```
elm-upgrade
module.js:471
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nick/npm_packages/lib/node_modules/elm-upgrade/upgrade.js:6:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Error went away after I ran `npm install -g semver`.

I see that semver is a dev dependency. Maybe that needs to be changed to a regular ol' dependency?

**Comment by avh4** [comment]
Fixed in elm-upgrade 0.18.4
