### ISSUE TITLE
ENOTFOUND alpha.elm-lang.org

### ISSUE THREAD

**Issue by choonkeat** [avh4/elm-upgrade#44]
### What worked

```
$ git clone https://github.com/avh4/elm-upgrade.git
$ npm install -g `pwd`
$ npm install -g elm-format@rc
$ elm-upgrade
```

### What didn't work

Instructions at https://github.com/avh4/elm-upgrade/tree/rc#how-to-use-it

> ```
> $ npm install -g elm-format@rc elm-upgrade@rc
> $ elm-upgrade
> ```

```
**NOT FOR SHARING.** Do not post about the alpha/rc version of elm-upgrade on reddit, twitter, HN, discourse, etc.
**NOT FOR SHARING.** Learn why here: <https://www.deconstructconf.com/2017/evan-czaplicki-on-storytelling>

{ RequestError: getaddrinfo ENOTFOUND alpha.elm-lang.org alpha.elm-lang.org:443
    at ClientRequest.req.once.err ($HOME/.nvm/versions/node/v8.11.2/lib/node_modules/elm-upgrade/node_modules/got/index.js:73:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOTFOUND',
  message: 'getaddrinfo ENOTFOUND alpha.elm-lang.org alpha.elm-lang.org:443',
  host: 'alpha.elm-lang.org',
  hostname: 'alpha.elm-lang.org',
  method: 'GET',
  path: '/search.json' }
ERROR: Unable to connect to https://alpha.elm-lang.org.  Please try again later.
```

I suspect all can be fixed by updating npm?

**Comment by avh4** [comment]
The rc package server has been shut down now that Elm 0.19 has been release.  The 0.19 version of elm-upgrde hasn't been published yet, but I'm hoping to have it published in a few hours.
