### ISSUE TITLE
npx elm-upgrade fail

### ISSUE THREAD

**Issue by ChetHarrison** [avh4/elm-upgrade#71]
I got this error when attempting `npx elm-upgrade`

```
$ npx elm-upgrade
{ HTTPError: Response code 404 (Not Found)
    at stream.catch.then.data (/usr/local/lib/node_modules/elm-upgrade/node_modules/got/index.js:129:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  message: 'Response code 404 (Not Found)',
  host: 'package.elm-lang.org',
  hostname: 'package.elm-lang.org',
  method: 'GET',
  path: '/new-packages',
  statusCode: 404,
  statusMessage: 'Not Found' }
ERROR: Unable to connect to http://package.elm-lang.org.  Please try again later.
```

Any thoughts?

**Comment by avh4** [comment]
`/new-packages` is the path for the Elm 0.18 package website... it looks like it's running an old version of elm-upgrade?   I guess maybe I don't fully understand how npx works.  Does `npx -p elm-upgrade@elm0.19.0 elm-upgrade` work?

**Comment by ChetHarrison** [comment]
Yes. Thank you
